export type BlogPost = {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  date: string;
  readingTime: string;
  author: string;
  content: string[];
};

export const blogPosts: BlogPost[] = [
  {
    slug: "ceh-v13-ai-what-changed",
    title: "CEH v13 AI: What Changed and Why It Matters for Your Career",
    excerpt:
      "EC-Council's latest CEH revision brings AI-powered attack simulation into the core curriculum. Here's what's new and how it affects hiring expectations in India.",
    category: "Certification",
    date: "2026-06-18",
    readingTime: "6 min read",
    author: "Vikram Aditya Rao",
    content: [
      "For over a decade, the Certified Ethical Hacker credential has been the entry point most Indian employers look for when hiring penetration testers and security analysts. CEH v13 AI is the most significant revision to the syllabus since the exam introduced practical lab components, and it changes what recruiters expect from a certified candidate.",
      "The headline addition is AI-powered attack simulation. Modules now cover how adversaries use generative models to accelerate reconnaissance, craft convincing phishing content, and automate parts of exploit development. Candidates are tested not just on defending against these techniques, but on using AI-assisted tooling themselves to speed up legitimate penetration testing workflows — reconnaissance summarization, vulnerability triage, and report drafting.",
      "The second major shift is depth in cloud and container attack surfaces. Where earlier versions treated cloud security as a single module, CEH v13 AI integrates AWS and Azure misconfiguration scenarios throughout the scanning, enumeration, and post-exploitation modules, reflecting how much production infrastructure has moved off traditional on-premise networks.",
      "For hiring managers, this means a CEH v13 AI badge now signals more than familiarity with Nmap and Metasploit — it signals a candidate who has practiced against AI-augmented attacker behavior and modern cloud environments. At PenCap, our CEH v13 AI track was rebuilt module-by-module around this new blueprint, with live lab exercises that mirror the exact scenario types tested in the certification exam.",
      "If you're currently CEH-certified under an earlier version, it's worth a refresher cohort — the skills gap between v12 and v13 AI is large enough that most Tier 1 recruiters in Chennai and Bengaluru are now explicitly screening for the newer version on penetration testing job postings.",
    ],
  },
  {
    slug: "day-in-the-life-soc-analyst",
    title: "A Day in the Life of a SOC Analyst",
    excerpt:
      "From shift handover to incident escalation — a realistic walkthrough of what Tier 1 and Tier 2 analysts actually do inside a Security Operations Center.",
    category: "Careers",
    date: "2026-06-02",
    readingTime: "5 min read",
    author: "Meera Krishnamurthy",
    content: [
      "Most students picture a SOC analyst staring at a wall of red dashboards, reacting to sirens. The reality is calmer, more procedural, and far more interesting — a mix of pattern recognition, documentation discipline, and clear communication under pressure.",
      "A shift starts with handover: reading the previous analyst's notes, checking open tickets, and reviewing any alerts flagged for follow-up. Most of the first hour is spent triaging the overnight queue in the SIEM — sorting genuine anomalies from noise generated by scheduled jobs, patch windows, or known benign traffic.",
      "When something looks real — an unusual authentication pattern, a spike in outbound traffic to an uncommon destination, a flagged file hash — the analyst pulls the relevant logs, checks it against threat intelligence feeds, and decides whether it's a false positive, a policy violation, or an active incident. Tier 1 analysts handle the first two categories directly; genuine incidents get escalated to Tier 2 with a clear write-up of what was observed, what was checked, and why it's being escalated.",
      "The rest of the day is a mix of proactive threat hunting (searching for patterns that automated rules might miss), tuning detection rules to reduce false positives, and sitting in on retrospectives for incidents closed the previous week. Documentation is constant — every action taken on an alert needs to be defensible later, both for compliance and for training the next analyst who picks up a similar case.",
      "It's a role built on repetition and discipline more than dramatic heroics, which is exactly why the SOC Analyst track at PenCap runs entirely inside a live-traffic lab environment — muscle memory for triage, escalation, and documentation is what actually gets graduates hired and retained.",
    ],
  },
  {
    slug: "network-engineer-to-cybersecurity",
    title: "How Network Engineers Can Transition Into Cybersecurity",
    excerpt:
      "Your networking background is a head start, not a detour. Here's the exact skill gap to close and the fastest path into a security role.",
    category: "Careers",
    date: "2026-05-20",
    readingTime: "7 min read",
    author: "Arjun Balachandran",
    content: [
      "Network engineers routinely underestimate how close they already are to a cybersecurity role. You already understand TCP/IP, routing, VLANs, firewalls, and how traffic actually moves through an enterprise network — that's the hardest part of the security curriculum for most career changers, and you've already lived it.",
      "The gap isn't networking knowledge — it's attacker and defender mindset. A network engineer is trained to make traffic flow correctly and reliably. A security professional is trained to ask: how would this configuration be abused, and how would I detect that abuse happening right now? That reframing is a matter of structured practice, not years of new study.",
      "The fastest path we see students take is choosing a lane first. If you enjoy building and hardening infrastructure, the SOC Analyst track — with its focus on monitoring, detection engineering and incident response — will feel like a natural extension of your existing operations experience. If you're drawn to finding and exploiting weaknesses, CEH v13 AI channels that curiosity into a structured, certifiable skill set.",
      "Either way, the specific gap to close is hands-on exposure to attacker tooling and SIEM platforms — things you're unlikely to have touched in a pure networking role. That's precisely why our programs are lab-first: you're not reading about Nmap scans or Splunk correlation rules, you're running them against live simulated environments from week one.",
      "Most network engineers who go through our Master Program are placement-ready in security roles within the same total structure — 9 months — carrying a salary premium over their previous networking role, because employers value the operational maturity you bring on day one far more than a security-only background without any production experience.",
    ],
  },
  {
    slug: "top-cybersecurity-job-roles-india-2026",
    title: "Top 6 Cybersecurity Job Roles in India for 2026",
    excerpt:
      "Salary ranges, required skills, and demand outlook for the most in-demand cybersecurity job titles hiring right now across Indian IT and product companies.",
    category: "Industry Insights",
    date: "2026-05-05",
    readingTime: "8 min read",
    author: "Lakshmi Narayanan",
    content: [
      "India's cybersecurity hiring has moved past a niche specialization and into a standard line item for every mid-to-large enterprise, IT services firm, and product company. Based on the roles we place graduates into most consistently, here's where the demand — and the money — actually is in 2026.",
      "SOC Analyst (Tier 1/2) remains the highest-volume entry point, with salaries typically ranging ₹4.5–9 LPA depending on shift structure and employer tier. IT services majors and managed security service providers are hiring the largest volumes here, often in 24x7 rotational shifts.",
      "Penetration Tester and Vulnerability Analyst roles command a premium for candidates who can produce clean, client-ready reports in addition to finding vulnerabilities — ₹5–11 LPA is typical, rising quickly with 2-3 years of engagement experience and a recognized certification like CEH.",
      "Threat Intelligence Analyst is a smaller but fast-growing category, particularly at financial services and product companies building in-house security teams, paying ₹5.5–10 LPA for candidates comfortable synthesizing intelligence feeds into actionable detection rules.",
      "Security Engineer roles — designing and implementing controls across cloud and on-prem infrastructure — sit at the top of the entry-to-mid range, ₹6–14 LPA, and increasingly require some cloud security exposure (AWS or Azure) alongside core security fundamentals.",
      "GRC Analyst roles, focused on compliance frameworks like ISO 27001 and SOC 2, pay ₹5–9 LPA and are in particularly high demand at consulting firms and companies preparing for international clients that require formal security audits.",
      "Across every one of these roles, the single biggest differentiator between candidates at the same experience level isn't certifications alone — it's demonstrable hands-on lab experience that a candidate can speak to specifically in interviews.",
    ],
  },
  {
    slug: "building-your-first-home-lab",
    title: "Building Your First Ethical Hacking Home Lab",
    excerpt:
      "A practical, budget-friendly guide to setting up Kali Linux, vulnerable VMs and a safe practice network before your first CEH class.",
    category: "How-To",
    date: "2026-04-22",
    readingTime: "9 min read",
    author: "Vikram Aditya Rao",
    content: [
      "You don't need enterprise hardware to start practicing ethical hacking safely. A laptop with 16GB of RAM and a free hypervisor is enough to build a legitimate practice environment before you ever set foot in a classroom.",
      "Start with a Type-2 hypervisor — VirtualBox or VMware Workstation Player, both free for personal use. Install Kali Linux as your attacker machine; it ships with the vast majority of tools you'll use throughout CEH training pre-installed, so there's no need to assemble a toolkit manually.",
      "For targets, resist the urge to scan anything on the public internet — that's illegal without explicit authorization, full stop. Instead, download intentionally vulnerable virtual machines built for practice: Metasploitable2, OWASP's vulnerable web application projects, and the free tiers on platforms like TryHackMe and HackTheBox give you legal, structured targets at every skill level.",
      "Isolate your lab network. Configure your hypervisor's virtual network in 'host-only' or 'internal network' mode rather than bridged, so your practice traffic never touches your home network or the internet. This single step is what separates a responsible home lab from a liability.",
      "Once your attacker VM and at least one vulnerable target VM can see each other on the isolated network, start with the fundamentals: an Nmap scan to enumerate open ports and services, then research the specific service versions you find. This loop — scan, research, attempt, document — is the actual daily rhythm of penetration testing, and building the habit at home means you walk into your first CEH lab session already comfortable with the tooling.",
      "When you join PenCap's CEH v13 AI track, this home setup becomes a genuine head start — our mentors can take you straight into intermediate exercises instead of spending your first week just learning where the buttons are.",
    ],
  },
  {
    slug: "why-small-batch-size-matters",
    title: "Why Batch Size Is the Most Overlooked Factor in Choosing a Training Institute",
    excerpt:
      "Course content is easy to copy. Mentor attention is not. Here's the case for why we cap every PenCap batch at 15 students.",
    category: "Industry Insights",
    date: "2026-04-10",
    readingTime: "4 min read",
    author: "Lakshmi Narayanan",
    content: [
      "Every cybersecurity training institute in India can publish a similar-looking syllabus — the CEH blueprint and SOC analyst skill set are, after all, publicly documented. What's much harder to copy is what happens in the room while that syllabus is being taught.",
      "In a batch of 40 or 50 students, a mentor has minutes, not hours, to spend on any individual learner's specific confusion. Questions that would take 90 seconds to resolve one-on-one get deferred, generalized, or simply dropped because the class has to move on.",
      "We cap every PenCap batch at 15 students for a specific reason: it's the largest group size where a single mentor can still watch every screen during a live lab exercise, notice who's stuck on the same step for too long, and adjust the pace of the session in real time rather than after the fact.",
      "It also changes the interview preparation experience. Mock interviews and technical whiteboard sessions are genuinely personal at this size — mentors remember your specific weak points across sessions and target practice accordingly, instead of running through a generic checklist.",
      "When you're comparing institutes, ask directly about batch size and get it in writing. It's the single number most correlated with how much of the published syllabus you'll actually absorb, and it's also the reason our placement outcomes hold up as consistently as they do.",
    ],
  },
];

export function getBlogBySlug(slug: string) {
  return blogPosts.find((post) => post.slug === slug);
}
